name: rocket_pocket
description: "Rocket Pocket is a simple, fast and secure web app for Android and iOS. It is designed to provide a better mobile experience with the Rocketseat website."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          style: normal
